[project]
name = "sqcli"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "prompt-toolkit>=3.0.52",
    "pygments>=2.19.2",
    "pyinstaller>=6.18.0",
    "rich>=14.2.0",
]
